### PR TITLE
[Issue #3426]: Reproduction of Lerna v6 and Module Federation issue

### PR DESCRIPTION
**Pull request by iholovin**
This repro has a `host` package and 9 MFEs.

- Run `start` script from the root
- Observe lerna logs — only 8 out of 10 dev servers are running
- Open `localhost:3000` -> DevTools [Network] -> See that two `remoteEntry.js` files were not loaded because corresponding dev-servers are not running

### CODE REVIEW

**Comment by JamesHenry** [comment]
Hi @iholovin this workspace seems to have an undesirable mixture of multiple major versions of yarn in it.

You have a `.yarnrc.yml` with the node_modules linker specified, suggesting you are using yarn 2 or 3, but then you have yarn v1 lockfiles including nested ones (which are not desired at all).

When I fix up the yarn inconsistencies and remove the nested lockfiles, everything works as expected:

image

image

**Comment by iholovin** [comment]
Hey @JamesHenry. It was an honest mistake — I had the wrong version of `node` selected. I fixed it and pushed new commit — now there is only one root `yarn.lock` with proper version, as it supposed to be. Tested it locally — still starts only 8 mfe's out of 10...

**Comment by JamesHenry** [comment]
I'm sorry maybe something ended up in a mess because of the gh CLI.

I ended up creating a branch called `iholovin/main` it seems...

Please try it out:

https://github.com/lerna/repro/compare/main...iholovin:lerna-repro-mf:iholovin/main?expand=1

The only other real difference I can see is that I have a 10 core CPU and you have an 8 core one:

```
CPU: (10) arm64 Apple M1 Max
```

Is the behaviour any different if you explicitly pass `--parallel`?

**Comment by JamesHenry** [comment]
I really think this CPU count point is going to be it.

Lerna's default concurrency has always been based on CPU count:

image

When you don't specify `--parallel` the task runner will fallback to the setting for concurrency, which has a default based on the CPU count as you can see above.

So please try with `--parallel`

**Comment by iholovin** [comment]
@JamesHenry `--parallel` had no effect, but the `--concurrency=10` thing did the trick — I was able to run all 10 microfrontends. Thanks!

**Pull request closed without merging**
